### PR TITLE
added arabic translation

### PR DESCRIPTION
**Pull request by AliMostafaRadwan**

### CODE REVIEW

**Comment by zhiyiYo** [comment]
Thank you

**Comment by zhiyiYo** [comment]
Hi, I found that some messages are not translated
image

**Comment by AliMostafaRadwan** [comment]
i translated the English ts file only
image

**Comment by AliMostafaRadwan** [comment]
> The English ts file is out of date

sure then, ill translate the Chinese later this week

**Comment by zhiyiYo** [comment]
Thanks

**Pull request merged**
